server:
  servlet:
    context-path: /springboot-mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practicedb?useSSL=false
    username: root
    password: nisum
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update